// module.exports = {
//   docs: ["index",
//     { "Développement web": ["dev_web/docusaurus"] },
//     { "Développement logiciel": [] },
//     { "SAP": ["sap/sapui5"] }
//   ],
//   code: ["code/intro",
//     { "SAP": ["code/abap"] }
//   ]
// };

module.exports = {
  docs: [
    "index",
    {
      type: "category",
      label: "Développement web",
      items: [
        {
          type: "autogenerated", dirName: "dev_web"
        }
      ]
    },
    /*     {
          type: "category",
          label: "Développement logiciel",
          items: []
        }, */
    {
      type: "category",
      label: "SAP",
      items: [
        {
          type: "autogenerated", dirName: "sap"
        }
      ]
    }
  ],
  code: [
    "code/intro",
    {
      type: "category",
      label: "SAP",
      items: ["code/abap"]
    }
  ]
};