module.exports = {
  docs: [
    "index",
    {
      type: "category",
      label: "Générateurs de site statique",
      items: [
        {
          type: "autogenerated", dirName: "ssg"
        }
      ]
    },
  ]
};